# Generated by Django 5.0 on 2023-12-28 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('agency', models.PositiveIntegerField()),
                ('cnpj', models.CharField(max_length=18)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='financial.bank')),
            ],
        ),
    ]
