# Generated by Django 5.0 on 2023-12-30 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixAccount',
            fields=[
                ('bankAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='financial.bankaccount')),
                ('key', models.CharField()),
                ('clientId', models.CharField()),
                ('secretId', models.CharField()),
                ('expire_time', models.PositiveIntegerField()),
            ],
        ),
    ]
