# Generated by Django 5.0 on 2024-01-07 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_invoicetoreceive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelPix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentDate', models.DateField()),
                ('value', models.FloatField()),
                ('status', models.PositiveSmallIntegerField()),
                ('sequence', models.PositiveSmallIntegerField()),
                ('invoiceToReceive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.invoicetoreceive')),
                ('pixCharge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial.pixcharge')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
